#!/usr/bin/env ruby
require "bundle/setup"
require_relative "lib/my_project"
require "sequel"
require "irb"

def config
  return @config if @config
  config_path = File.expand_path("../config/application.yml", __FILE__)
  @config = YAML.load_file(config_path)
end

DB = Sequel.connect(config[:database])

IRB.start